Repository celenium-io/celestia-indexer, pull requests merged in 2023-11, with the labels that each got.

#18 Fix: nil pointer with no content
  cmd/api/handler/address.go
  cmd/api/handler/block.go
  cmd/api/handler/block_test.go
  cmd/api/handler/constant.go
  cmd/api/handler/namespace.go
  cmd/api/handler/search.go
  cmd/api/handler/tx.go
Labels: bug

#19 Fix: pfb count computing
  pkg/indexer/decode/handle/blob.go
  pkg/indexer/decode/handle/test/blob_test.go
Labels: bug

#21 Fix: add excluded_msg_types to tx.List
  cmd/api/docs/docs.go
  cmd/api/docs/swagger.json
  cmd/api/docs/swagger.yaml
  cmd/api/handler/requests.go
  cmd/api/handler/tx.go
  cmd/api/handler/tx_test.go
  internal/storage/postgres/scopes.go
  internal/storage/postgres/storage_test.go
  internal/storage/tx.go
Labels: bug

#22 Feature: add endpoint for receiving block messages
  cmd/api/docs/docs.go
  cmd/api/docs/swagger.json
  cmd/api/docs/swagger.yaml
  cmd/api/handler/block.go
  cmd/api/handler/block_test.go
  cmd/api/handler/requests.go
  cmd/api/handler/responses/message.go
  cmd/api/handler/websocket/client.go
  cmd/api/init.go
  internal/storage/message.go
  internal/storage/mock/address.go
  internal/storage/mock/balance.go
  internal/storage/mock/block.go
  internal/storage/mock/block_stats.go
  internal/storage/mock/constant.go
  internal/storage/mock/denom_metadata.go
  internal/storage/mock/event.go
  internal/storage/mock/generic.go
  internal/storage/mock/message.go
  internal/storage/mock/namespace.go
  internal/storage/mock/state.go
  internal/storage/mock/stats.go
  internal/storage/mock/tx.go
  internal/storage/mock/validator.go
  internal/storage/postgres/message.go
  internal/storage/postgres/scopes.go
  internal/storage/postgres/storage_test.go
  pkg/indexer/parser/parseTxs_test.go
  pkg/node/mock/api.go
  pkg/types/hex.go
Labels: feature

#23 Improve sentry usage
  .env.example
  cmd/api/init.go
  cmd/api/sentry_middleware.go
  go.mod
  go.sum
Labels: feature

#9 [WIP] Fix: notify closed client
  cmd/api/handler/websocket/client.go
  cmd/api/handler/websocket/client_test.go
  cmd/api/init.go
Labels: bug

#26 fix regexp release actions
  .github/workflows/prerelease.yml
  .github/workflows/release.yml
Labels: bug, CI

#27 Split release on 2 jobs
  .github/workflows/prerelease.yml
  .github/workflows/release.yml
Labels: bug, CI

#28 Add snetry action parameters
  .github/workflows/prerelease.yml
  .github/workflows/release.yml
Labels: bug, CI

#29 Fix: duplicate message addresses
  internal/storage/message_address.go
  pkg/indexer/storage/message.go
  pkg/indexer/storage/message_test.go
Labels: bug

#30 Fix: check channel message pointer
  cmd/api/handler/websocket/channel.go
Labels: bug

#31 remove latest tag from release
  .github/workflows/release.yml
Labels: CI

#33 CLS 85 instructions for self deployment
  .env.example
  README.md
  docker-compose.yml
  pkg/indexer/decode/message.go
Labels: docs, CI

#35 fixed format of env vars in readme
  README.md
Labels: docs

#36 Feature: add idle timeout to API
  cmd/api/init.go
  go.mod
  go.sum
Labels: optimization, dependency

#37 Upgrade indexer SDK to v0.0.4
  go.mod
  go.sum
Labels: dependency

#38 Fix: bad request status code on validation error in stats API
  cmd/api/handler/stats.go
  internal/storage/errors.go
  internal/storage/stats.go
Labels: bug

#39 Optimization: receive blocks via websocket
  .env.example
  build/dipdup.yml
  pkg/indexer/indexer.go
  pkg/indexer/receiver/receiver.go
  pkg/indexer/receiver/receiver_test.go
  pkg/indexer/receiver/sync.go
Labels: feature

#40 Feature: make views for extended statistics
  .env.example
  .run/API.run.xml
  .run/Indexer.run.xml
  .vscode/launch.json
  Makefile
  build/api/Dockerfile
  build/indexer/Dockerfile
  cmd/api/docs/docs.go
  cmd/api/docs/swagger.json
  cmd/api/docs/swagger.yaml
  cmd/api/handler/responses/stats.go
  cmd/api/handler/responses/stats_test.go
  cmd/api/handler/stats.go
  cmd/api/handler/stats_test.go
  cmd/api/init.go
  cmd/api/main.go
  configs/dipdup.yml
  database/views/gas_price_candlesticks_hourly.sql
  database/views/tx_count_hourly.sql
  docker-compose.yml
  internal/storage/mock/stats.go
  internal/storage/namespace_message.go
  internal/storage/postgres/block_stats_test.go
  internal/storage/postgres/core.go
  internal/storage/postgres/stats.go
  internal/storage/postgres/stats_test.go
  internal/storage/postgres/storage_test.go
  internal/storage/postgres/transaction_test.go
  internal/storage/postgres/views.go
  internal/storage/state.go
  internal/storage/stats.go
  internal/storage/views.go
  pkg/indexer/config/config.go
  pkg/indexer/indexer.go
  pkg/indexer/rollback/rollback_test.go
  pkg/indexer/storage/storage_test.go
Labels: feature

#41 Feature: sorting active namespaces by pfb count, time or size
  cmd/api/docs/docs.go
  cmd/api/docs/swagger.json
  cmd/api/docs/swagger.yaml
  cmd/api/handler/namespace.go
  cmd/api/handler/namespace_test.go
  cmd/api/handler/responses/namespace.go
  internal/storage/generic.go
  internal/storage/mock/generic.go
  internal/storage/mock/namespace.go
  internal/storage/namespace.go
  internal/storage/postgres/index.go
  internal/storage/postgres/namespace.go
  internal/storage/postgres/storage_test.go
  internal/storage/postgres/transaction.go
  internal/storage/postgres/transaction_test.go
  pkg/indexer/decode/handle/blob.go
  pkg/indexer/decode/handle/test/blob_test.go
  pkg/indexer/decode/message.go
  pkg/indexer/receiver/sync.go
  pkg/indexer/rollback/namespace.go
  test/data/namespace.yml
  test/data/rollback/namespace.yml
Labels: feature

#42 Feature: add gas estimation for pay for blob endpoint
  cmd/api/docs/docs.go
  cmd/api/docs/swagger.json
  cmd/api/docs/swagger.yaml
  cmd/api/handler/gas.go
  cmd/api/handler/gas_test.go
  cmd/api/init.go
Labels: feature

#32 Feature: cache endpoint responses
  .env.example
  cmd/api/cache/cache.go
  cmd/api/cache/cache_test.go
  cmd/api/cache/response.go
  cmd/api/config.go
  cmd/api/handler/websocket/channel.go
  cmd/api/handler/websocket/manager.go
  cmd/api/init.go
  configs/dipdup.yml
Labels: feature

#43 Fix: add cache skipper
  cmd/api/cache/cache.go
  cmd/api/init.go
  cmd/api/init_test.go
Labels: bug

#44 Feature: detect blob content type
  cmd/api/docs/docs.go
  cmd/api/docs/swagger.json
  cmd/api/docs/swagger.yaml
  cmd/api/handler/namespace.go
  cmd/api/handler/responses/blob.go
Labels: feature

#45 Feature: add namespace usage endpoint
  cmd/api/handler/address_test.go
  cmd/api/handler/responses/stats.go
  cmd/api/handler/stats.go
  cmd/api/handler/stats_test.go
  cmd/api/init.go
Labels: feature

#46 Feature: block stats views
  cmd/api/docs/docs.go
  cmd/api/docs/swagger.json
  cmd/api/docs/swagger.yaml
  cmd/api/handler/responses/block.go
  cmd/api/handler/responses/stats.go
  cmd/api/handler/responses/stats_test.go
  cmd/api/handler/stats.go
  cmd/api/handler/stats_test.go
  cmd/api/init.go
  cmd/api/main.go
  cmd/indexer/main.go
  database/views/00_block_stats_by_minute.sql
  database/views/01_block_stats_by_hour.sql
  database/views/02_block_stats_by_day.sql
  database/views/03_block_stats_by_year.sql
  database/views/04_block_stats_by_month.sql
  database/views/05_block_stats_by_week.sql
  database/views/gas_price_candlesticks_hourly.sql
  database/views/tx_count_hourly.sql
  internal/storage/block_stats.go
  internal/storage/mock/stats.go
  internal/storage/postgres/stats.go
  internal/storage/postgres/stats_test.go
  internal/storage/postgres/storage_test.go
  internal/storage/postgres/views.go
  internal/storage/stats.go
  internal/storage/views.go
  pkg/indexer/parser/parse.go
  test/data/block_stats.yml
  test/data/rollback/block_stats.yml
Labels: feature

#48 Feature: add event types
  cmd/api/docs/docs.go
  cmd/api/docs/swagger.json
  cmd/api/docs/swagger.yaml
  internal/storage/types/event_type.go
  internal/storage/types/event_type_enum.go
Labels: feature

#49 Feature: decode namespace id
  cmd/api/docs/docs.go
  cmd/api/docs/swagger.json
  cmd/api/docs/swagger.yaml
  cmd/api/handler/responses/namespace.go
  cmd/api/handler/responses/namespace_test.go
Labels: feature

#50 Fix: decode namespace id
  cmd/api/handler/responses/namespace.go
  cmd/api/handler/responses/namespace_test.go
Labels: bug

#51 Refactoring: make bus for postgres listener
  cmd/api/bus/dispatcher.go
  cmd/api/bus/observer.go
  cmd/api/cache/cache.go
  cmd/api/cache/cache_test.go
  cmd/api/docs/docs.go
  cmd/api/handler/websocket/channel.go
  cmd/api/handler/websocket/channel_test.go
  cmd/api/handler/websocket/manager.go
  cmd/api/handler/websocket/processors.go
  cmd/api/handler/ws_test.go
  cmd/api/init.go
  cmd/api/main.go
Labels: refactoring

#52 Feature: extended stats endpoint for namespace
  cmd/api/docs/docs.go
  cmd/api/docs/swagger.json
  cmd/api/docs/swagger.yaml
  cmd/api/handler/stats.go
  cmd/api/handler/stats_test.go
  cmd/api/init.go
  database/views/06_namespace_stats_by_hour.sql
  database/views/07_namespace_stats_by_day.sql
  database/views/08_namespace_stats_by_year.sql
  database/views/09_namespace_stats_by_month.sql
  database/views/10_namespace_stats_by_week.sql
  internal/storage/mock/stats.go
  internal/storage/namespace_message.go
  internal/storage/postgres/core.go
  internal/storage/postgres/stats.go
  internal/storage/postgres/stats_test.go
  internal/storage/stats.go
  internal/storage/views.go
  pkg/indexer/genesis/save.go
  pkg/indexer/storage/message.go
Labels: feature

#54 Fix: namespace usage name
  cmd/api/handler/responses/stats.go
  cmd/api/handler/stats_test.go
Labels: bug

#53 Feature: gas tracker endpoint
  cmd/api/docs/docs.go
  cmd/api/docs/swagger.json
  cmd/api/docs/swagger.yaml
  cmd/api/gas/data.go
  cmd/api/gas/data_test.go
  cmd/api/gas/tracker.go
  cmd/api/gas/tracker_test.go
  cmd/api/handler/gas.go
  cmd/api/handler/gas_test.go
  cmd/api/handler/responses/gas.go
  cmd/api/init.go
  cmd/api/main.go
  internal/storage/block_stats.go
  internal/storage/mock/block_stats.go
  internal/storage/mock/tx.go
  internal/storage/postgres/block_stats.go
  internal/storage/postgres/block_stats_test.go
  internal/storage/postgres/storage_test.go
  internal/storage/postgres/tx.go
  internal/storage/tx.go
Labels: feature

#55 Fix: add request timeout
  pkg/indexer/receiver/worker.go
  pkg/node/rpc/api.go
Labels: bug

#56 Fix: duplicate consensus address
  internal/storage/postgres/index.go
  internal/storage/validator.go
Labels: bug

#58 Fix: from and to filters in stats
  internal/storage/postgres/stats.go
  internal/storage/postgres/stats_test.go
Labels: bug

#59 Feature: add top parameter to namespace usage
  cmd/api/docs/docs.go
  cmd/api/docs/swagger.json
  cmd/api/docs/swagger.yaml
  cmd/api/handler/responses/stats.go
  cmd/api/handler/stats.go
  cmd/api/handler/stats_test.go
Labels: feature
