Repository celenium-io/celestia-indexer, pull requests merged in 2024-09, with the labels that each got.

#273 Refactoring: remove blob saving
  configs/dipdup.yml
  go.mod
  go.sum
  pkg/indexer/blob_saver/module.go
  pkg/indexer/blob_saver/module_test.go
  pkg/indexer/config/config.go
  pkg/indexer/indexer.go
  pkg/indexer/parser/blob.go
  pkg/indexer/parser/parse.go
  pkg/indexer/parser/parseTxs.go
Labels: refactoring

#274 Feature: additional filters for blob requests
  cmd/api/docs/swagger.json
  cmd/api/handler/address.go
  cmd/api/handler/address_test.go
  cmd/api/handler/namespace.go
  cmd/api/handler/namespace_test.go
  cmd/api/handler/responses/blob.go
  cmd/api/handler/rollup.go
  cmd/api/init.go
  internal/storage/address.go
  internal/storage/blob_log.go
  internal/storage/mock/address.go
  internal/storage/postgres/address.go
  internal/storage/postgres/address_test.go
  internal/storage/postgres/blob_log.go
  internal/storage/postgres/blob_log_test.go
  internal/storage/postgres/scopes.go
Labels: feature

#275 Deps: celestia-app
  go.mod
  go.sum
Labels: dependency

#277 Feature: endpoint with all blobs
  cmd/api/docs/swagger.json
  cmd/api/handler/address.go
  cmd/api/handler/namespace.go
  cmd/api/handler/namespace_test.go
  cmd/api/handler/responses/blob.go
  cmd/api/handler/rollup.go
  cmd/api/handler/stats.go
  cmd/api/handler/validator.go
  cmd/api/init.go
  cmd/api/main.go
  cmd/api/routes_test.go
  internal/storage/blob_log.go
  internal/storage/mock/blob_log.go
  internal/storage/postgres/blob_log.go
  internal/storage/postgres/blob_log_test.go
  internal/storage/postgres/scopes.go
Labels: feature

#278 Hot fixes: validator addresses and CSRF
  cmd/api/handler/address.go
  cmd/api/init.go
  internal/storage/address.go
  internal/storage/mock/address.go
  internal/storage/postgres/address.go
  internal/storage/postgres/address_test.go
Labels: bug

#279 Feature: add new event types
  cmd/api/handler/constant_test.go
  internal/storage/types/event_type.go
  internal/storage/types/event_type_enum.go
Labels: feature

#280 Fill swagger docs
  cmd/api/docs/swagger.json
  cmd/api/main.go
Labels: docs

#281 Api auto gen workflow
  .github/workflows/apiwrapper.yml
Labels: CI

#282 Fix: make /v1/blob authorizable in docs
  cmd/api/docs/swagger.json
  cmd/api/handler/namespace.go
  cmd/api/main.go
Labels: docs

#283 Fix: swagger for /v1/blob endpoint
  cmd/api/docs/swagger.json
  cmd/api/handler/namespace.go
Labels: docs

#284 Feature: add rollup columns
  cmd/api/docs/swagger.json
  cmd/api/handler/responses/rollup.go
  cmd/api/handler/rollup_auth.go
  internal/storage/postgres/custom_types.go
  internal/storage/postgres/transaction.go
  internal/storage/postgres/transaction_test.go
  internal/storage/rollup.go
  internal/storage/types/rolllup.go
  internal/storage/types/rolllup_enum.go
Labels: feature

#285 Fix: default blob log sorting
  internal/storage/postgres/scopes.go
Labels: bug
