Repository celenium-io/celestia-indexer, pull requests merged in 2025-04, with the labels that each got.

#370 Fix: update api docs
  cmd/api/docs/swagger.json
Labels: docs

#369 Feature: size groups
  cmd/api/docs/swagger.json
  cmd/api/gas/mock.go
  cmd/api/handler/responses/stats.go
  cmd/api/handler/stats.go
  cmd/api/handler/stats_test.go
  cmd/api/init.go
  cmd/api/routes_test.go
  internal/storage/mock/stats.go
  internal/storage/postgres/stats.go
  internal/storage/postgres/stats_test.go
  internal/storage/stats.go
Labels: feature

#371 Add settled property to rollup
  cmd/api/handler/responses/rollup.go
  cmd/api/handler/rollup_auth.go
  internal/storage/postgres/transaction.go
  internal/storage/postgres/transaction_test.go
  internal/storage/rollup.go
  test/data/rollback/rollup.yml
  test/data/rollup.yml
Labels: feature

#373 Deps: update and refactoring
  cmd/indexer/main.go
  go.mod
  go.sum
  internal/storage/postgres/sentry_hook.go
  pkg/indexer/decode/context/context.go
  pkg/indexer/decode/handle/test/bank_test.go
  pkg/indexer/decode/handle/test/staking_test.go
  pkg/indexer/decode/handle/test/vesting_test.go
Labels: dependencies

#374 Fix: workflow permissions
  .github/workflows/apiwrapper.yml
  .github/workflows/build.yml
  .github/workflows/license.yml
  .github/workflows/prerelease.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
Labels: bug

#375 Refactoring: allow rollup providers without address
  cmd/api/handler/rollup_auth.go
  cmd/api/handler/validators.go
  cmd/api/handler/validators_test.go
  database/views/22_leaderboard.sql
  database/views/24_leaderboard_day.sql
  database/views/25_da_change.sql
  internal/storage/postgres/rollup.go
  internal/storage/postgres/stats.go
Labels: refactoring

#376 Optimization: get rollup blobs
  cmd/api/handler/rollup.go
  cmd/api/handler/rollup_test.go
Labels: optimization
