Repository celenium-io/celestia-indexer, pull requests merged in 2025-09, with the labels that each got.

#455 Refactoring: remove unused total_stake field from state and make API …
  cmd/api/docs/swagger.json
  cmd/api/handler/responses/hyperlane.go
  cmd/api/handler/responses/state.go
  cmd/api/handler/state_test.go
  go.mod
  go.sum
  internal/storage/state.go
  pkg/indexer/genesis/save.go
  pkg/indexer/rollback/rollback.go
  pkg/indexer/storage/delegations.go
  pkg/indexer/storage/state.go
  pkg/indexer/storage/state_test.go
  pkg/indexer/storage/storage.go
  test/data/rollback/state.yml
  test/data/state.yml
Labels: refactoring

#459 Fix: IBC relayers file
  build/api/Dockerfile
  cmd/api/assets/relayers_celestia.json
  cmd/api/init.go
Labels: bug

#461 Hotfix: parse new vote option format
  internal/storage/postgres/transaction.go
  internal/storage/postgres/transaction_test.go
  pkg/indexer/decode/tx_test.go
  pkg/indexer/parser/events/submit_proposal.go
  pkg/indexer/parser/events/submit_proposal_test.go
  pkg/indexer/parser/events/vote.go
  pkg/indexer/parser/events/vote_test.go
Labels: bug

#462 Fix: missing connection_id in ibc transfers
  internal/storage/postgres/migrations/20250910_set_missed_connection_id.go
  pkg/indexer/decode/event.go
  pkg/indexer/decode/event_test.go
  pkg/indexer/parser/events/acknowledgement.go
  pkg/indexer/parser/events/acknowledgement_test.go
Labels: bug

#464 Fix: parsing IBC ack
  pkg/indexer/parser/events/acknowledgement.go
  pkg/indexer/parser/events/acknowledgement_test.go
Labels: bug

#475 Refactoring: staking stats
  cmd/api/docs/swagger.json
  cmd/api/handler/ibc_test.go
  cmd/api/handler/stats.go
  cmd/api/handler/stats_test.go
  database/views/16_staking_by_hour.sql
  database/views/17_staking_by_day.sql
  database/views/18_staking_by_month.sql
  internal/storage/postgres/migrations/20250919_drop_old_staking_views.go
  internal/storage/postgres/stats.go
  internal/storage/postgres/stats_test.go
  internal/storage/stats.go
  test/data/rollback/staking_log.yml
  test/data/staking_log.yml
Labels: refactoring

#477 Optimization: add staking log type index
  internal/storage/postgres/index.go
Labels: optimization

#478 Hot-fix: hyperlane transfer empty amount
  pkg/indexer/decode/event.go
  pkg/indexer/decode/event_test.go
  pkg/indexer/parser/events/exec.go
Labels: bug

#485 Feature: proposal within the votes
  cmd/api/handler/proposals_test.go
  cmd/api/handler/responses/proposal.go
  cmd/api/handler/responses/vote.go
  internal/storage/postgres/vote.go
  internal/storage/postgres/vote_test.go
Labels: feature

#486 Fix: blob log sort
  internal/storage/postgres/blob_log.go
Labels: bug

#487 Deps: replace jsoniter to go-json
  cmd/api/bus/dispatcher.go
  internal/storage/types/msg_type_bitmask.go
  internal/storage/types/msg_type_bitmask_test.go
  internal/storage/types/packed_bytes.go
  pkg/indexer/storage/storage.go
  pkg/node/api/api.go
  pkg/node/rpc/api.go
  pkg/node/rpc/genesis.go
Labels: dependency
