Repository celenium-io/celestia-indexer, pull requests merged in 2025-01, with the labels that each got.

#326 Feature: add rollup tags
  build/api/Dockerfile
  build/indexer/Dockerfile
  build/quotes/Dockerfile
  cmd/api/docs/swagger.json
  cmd/api/handler/constant.go
  cmd/api/handler/constant_test.go
  cmd/api/handler/responses/constants.go
  cmd/api/handler/responses/rollup.go
  cmd/api/handler/rollup.go
  cmd/api/handler/rollup_auth.go
  cmd/api/handler/rollup_test.go
  cmd/api/init.go
  internal/storage/mock/rollup.go
  internal/storage/postgres/migrations/20241016_validator_rate.go
  internal/storage/postgres/migrations/20241025_signal_msg_types.go
  internal/storage/postgres/migrations/20241104_add_social_category.go
  internal/storage/postgres/migrations/20241213_balances_fix.go
  internal/storage/postgres/migrations/20250102_rollup_tags.up.sql
  internal/storage/postgres/migrations/migrations.go
  internal/storage/postgres/rollup.go
  internal/storage/postgres/rollup_test.go
  internal/storage/postgres/transaction.go
  internal/storage/postgres/transaction_test.go
  internal/storage/rollup.go
  internal/storage/types/rolllup.go
  pkg/node/mock/api.go
  test/data/rollup.yml
Labels: feature

#327 Optimization: websocket block channel
  cmd/api/bus/dispatcher.go
  cmd/api/handler/ws_test.go
  cmd/api/init.go
  internal/storage/block.go
  internal/storage/types/msg_type_bitmask.go
  internal/storage/types/msg_type_bitmask_test.go
  internal/storage/validator.go
  pkg/indexer/storage/storage.go
Labels: optimization

#328 Fix: websocket test
  cmd/api/handler/ws_test.go
Labels: bug

#329 Feature: add rollup verification
  cmd/api/admin_middleware.go
  cmd/api/handler/error.go
  cmd/api/handler/rollup_auth.go
  cmd/api/handler/validators.go
  cmd/api/handler/validators_test.go
  cmd/api/init.go
  cmd/api/routes_test.go
  database/views/22_leaderboard.sql
  internal/storage/api_key.go
  internal/storage/generic.go
  internal/storage/mock/api_key.go
  internal/storage/mock/rollup.go
  internal/storage/postgres/apikey.go
  internal/storage/postgres/apikey_test.go
  internal/storage/postgres/core.go
  internal/storage/postgres/migrations/20250113_rollup_verified.up.sql
  internal/storage/postgres/rollup.go
  internal/storage/postgres/rollup_test.go
  internal/storage/postgres/transaction.go
  internal/storage/rollup.go
  test/data/apikey.yml
  test/data/rollup.yml
  test/data/rollup_provider.yml
Labels: feature

#330 Feature: Tvl
  .run/API.run.xml
  .run/Indexer.run.xml
  cmd/api/handler/rollup.go
  cmd/api/handler/rollup_test.go
  cmd/api/handler/stats.go
  cmd/api/handler/stats_test.go
  cmd/api/init.go
  cmd/api/routes_test.go
  cmd/tvl/init.go
  cmd/tvl/main.go
  configs/dipdup.yml
  database/views/25_rollup_tvl_by_month.sql
  database/views/26_tvs_by_day.sql
  database/views/27_tvs_by_month.sql
  internal/storage/generic.go
  internal/storage/mock/namespace.go
  internal/storage/mock/rollup.go
  internal/storage/mock/stats.go
  internal/storage/mock/tvl.go
  internal/storage/postgres/core.go
  internal/storage/postgres/rollup.go
  internal/storage/postgres/rollup_test.go
  internal/storage/postgres/stats.go
  internal/storage/postgres/tvl.go
  internal/storage/postgres/tvl_test.go
  internal/storage/rollup.go
  internal/storage/stats.go
  internal/storage/tvl.go
  internal/storage/views.go
  internal/tvl/l2beat/api.go
  internal/tvl/l2beat/interface.go
  internal/tvl/l2beat/mock/interface.go
  internal/tvl/l2beat/tvl.go
  internal/tvl/lama/api.go
  internal/tvl/lama/interface.go
  internal/tvl/lama/mock/interface.go
  internal/tvl/lama/tvl.go
  pkg/tvl/module.go
  pkg/tvl/module_test.go
  test/data/tvl.yml
Labels: feature

#335 Refactoring: L2Beat change endpoint
  .vscode/launch.json
  Makefile
  internal/storage/mock/namespace.go
  internal/storage/mock/rollup.go
  internal/storage/mock/stats.go
  internal/storage/mock/tvl.go
  internal/storage/tvl.go
  internal/test_suite/helpers.go
  internal/tvl/l2beat/interface.go
  internal/tvl/l2beat/mock/interface.go
  internal/tvl/l2beat/timeframe.go
  internal/tvl/l2beat/timeframe_enum.go
  internal/tvl/l2beat/tvl.go
  internal/tvl/l2beat/tvl_test.go
  internal/tvl/lama/mock/interface.go
  pkg/tvl/module.go
  pkg/tvl/module_test.go
Labels: refactoring
